### ISSUE TITLE
hi python3.5 run chapter9 code got encoding problem

### ISSUE THREAD

**Issue by sherlockhoatszx** [chenyuntc/pytorch-book#2]
Hi,
try to run the chapter9 main.py code, and got the error as below:

File "main.py", line 212, in gen
    start_words = opt.start_words.encode('ascii', 'surrogateescape').decode('utf8')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

my enviorment is python 3.5,mac os, pytorch is 0.3.0.post4

**Comment by chenyuntc** [comment]
Thanks for your  report,  I'll  check it tonight.

**Comment by chenyuntc** [comment]
Sorry I can't reproduce  your problem in my linux server.

I guess the problem may be caused by the shell you use. In my shell arguments is passed to `fire` using binary, well your shell may use unicode (so there is no need to decode and encode).

anyway, I made a [commit](https://github.com/chenyuntc/pytorch-book/commit/9221e3d3d54fe3da28ce5ab8ce6712c657912a27) just now, hope it may be helpful: 

Please let me know if you have any question.

**Comment by sherlockhoatszx** [comment]
Hi, It was caused by character encoding and decoding different in python2 and python3.
i remend the code as 


++main.py line 219++


~~start_words = opt.start_words.encode('ascii', 'surrogateescape').decode('utf8')
prefix_words = opt.prefix_words.encode('ascii', 'surrogateescape').decode('utf8') if opt.prefix_words else None~~

`start_words = str.encode(opt.start_words)
 
prefix_words = str.encode(opt.prefix_words) if opt.prefix_words else None`

++main.py line229++

`start_words= start_words.replace(str.encode(','),str.encode(u'，'))\
                                     .replace(str.encode('.'),str.encode('。'))\
                                     .replace(str.encode('?'),str.encode('？'))`

Then it works.

My solution might not be the best practice ,for your reference.

**Comment by sherlockhoatszx** [comment]
Thanks for your in time reply.My problem got fixed.
